###
GET http://localhost:5000/orders/getAllorders
Authorization: bearer -Admin token-
Content-Type: application/json

{
   "email": "delilah_resto@gmail.com"
}

###
POST http://localhost:5000/orders/postOrder/6
Authorization: bearer -User token here-
Content-Type: application/json

{
   "email": "lenny_music@gmail.com"
}


###
###
POST http://localhost:5000/orders/postOrder/3
Authorization: bearer -Admin token-
Content-Type: application/json

{
   "email": "delilah_resto@gmail.com"
}

###
GET http://localhost:5000/orders/getOrderofUser
Authorization: bearer -User token here-
Content-Type: application/json

{
   "email": "lenny_music@gmail.com"
}

###
DELETE  http://localhost:5000/orders/removeProductsOrder/2
Authorization: bearer -User token here-
Content-Type: application/json

{
   "email": "lenny_music@gmail.com"
}

###
PUT http://localhost:5000/orders/selectPayMeth/1
Authorization: bearer -User token here-
Content-Type: application/json

{
   "email": "lenny_music@gmail.com"
}

###
PUT http://localhost:5000/orders/selectAddress/1
Authorization: bearer -User token here-
Content-Type: application/json

{
   "email": "lenny_music@gmail.com"
}


