###
GET http://localhost:5000/orders/getAllorders
Authorization: bearer -Admin token-
Content-Type: application/json

{
   "email": "delilah_resto@gmail.com"
}

###
POST http://localhost:5000/orders/postOrder/3
Authorization: bearer -user token-
Content-Type: application/json

{
   "email": "lenny_music@gmail.com"
}


###
###
POST http://localhost:5000/orders/postOrder/3
Authorization: bearer -Admin token-
Content-Type: application/json

{
   "email": "delilah_resto@gmail.com"
}

###
GET http://localhost:5000/orders/getOrderofUser
Authorization: bearer -User token-
Content-Type: application/json

{
   "email": "lenny_music@gmail.com"
}





