###
GET http://localhost:5000/pays
Authorization: bearer -User token here-
Content-Type: application/json

{
    "email": "lenny_music@gmail.com"
}

###
POST http://localhost:5000/pays/newPayMeth
Authorization: bearer -Admin token here-
Content-Type: application/json

{
    "email": "delilah_resto@gmail.com",
    "NamePay": "Pago Nequi"
}

###
PUT http://localhost:5000/pays/updatePayMeth/4
Authorization: bearer -Admin token here-
Content-Type:  application/json

{
    "email": "delilah_resto@gmail.com",
    "NamePay": "Pago PSI"
}

###
DELETE http://localhost:5000/pays/deletePayMeth/5
Authorization: bearer -Admin token here-
Content-Type: application/json

{
    "email": "delilah_resto@gmail.com"
}