###
GET http://localhost:5000/products
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGlsYWhfcmVzdG9AZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjI5NzYxNjM3fQ.epb7vO37Q0-K7gJcvU9mh8OgSXYleeQ77nzB2Z279Ic

###
POST http://localhost:5000/products/postProduct
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGlsYWhfcmVzdG9AZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjI5NzYxNjM3fQ.epb7vO37Q0-K7gJcvU9mh8OgSXYleeQ77nzB2Z279Ic
Content-Type: application/json

{
    "productName": "Agua mineral", 
    "price": 40
}

###
PUT http://localhost:5000/products/updateProduct/9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGlsYWhfcmVzdG9AZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjI5NzYxNjM3fQ.epb7vO37Q0-K7gJcvU9mh8OgSXYleeQ77nzB2Z279Ic
Content-Type:  application/json

{
    "productName": "Agua",
    "price": 37
}

###
DELETE http://localhost:5000/products/removeProduct/9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGlsYWhfcmVzdG9AZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjI5NzYxNjM3fQ.epb7vO37Q0-K7gJcvU9mh8OgSXYleeQ77nzB2Z279Ic