###
GET http://localhost:5000/products
Authorization: bearer -User token here-
Content-Type: application/json

{
    "email": "lenny_music@gmail.com"
}

###
POST http://localhost:5000/products/postProduct
Authorization: bearer -Admin token here-
Content-Type: application/json

{
    "email": "delilah_resto@gmail.com",
    "productName": "Agua mineral", 
    "price": 40
}

###
PUT http://localhost:5000/products/updateProduct/9
Authorization: bearer -Admin token here-
Content-Type:  application/json

{
    "email": "delilah_resto@gmail.com",
    "productName": "Agua",
    "price": 37
}

###
DELETE http://localhost:5000/products/removeProduct/9
Authorization: bearer -Admin token here-
Content-Type: application/json

{
    "email": "delilah_resto@gmail.com"
}