###
GET http://localhost:5000/products

###
POST http://localhost:5000/products/postProduct
Content-Type: application/json

{
    "productName": "Coca Cola", 
    "price": 40
}

###
PUT http://localhost:5000/products/updateProduct/8
Content-Type:  application/json

{
    "productName": "Agua",
    "price": 37
}

###
DELETE http://localhost:5000/products/removeProduct/3