###
GET http://localhost:5000/users

###
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "name": "Lenny Kravitz",
    "password": "elpapuNigga",
    "repeat_password": "elpapuNigga",
    "email": "lenny_music@gmail.com",
    "phone": 7896679
}

###
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "name": "Freddy Mercury",
    "password": "BestSinger",
    "repeat_password": "BestSinger",
    "email": "queen_freddy@gmail.com",
    "phone": 5678543
}

###
POST http://localhost:5000/users/logIn
Content-Type: application/json

{
    "email": "lenny_music@gmail.com",
    "password": "elpapuNigga"
}

###
POST http://localhost:5000/users/logIn
Content-Type: application/json

{   
    "email": "queen_freddy@gmail.com",
    "password": "BestSinger"
}


###
POST http://localhost:5000/users/logIn
Content-Type: application/json

{   
    "email": "delilah_resto@gmail.com",
    "password": "delilahKey1234"
}


###
DELETE http://localhost:5000/users/removeUser/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbGlsYWhfcmVzdG9AZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjI5NDcxMDUxfQ.j7xy_oI3LQRnRS5mg7Hz_IA3JBBukTY-Uq_VqZi__4g