###
GET http://localhost:5000/users/allUsers
Authorization: bearer -Admin token here-
###
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "name": "Lenny Kravitz",
    "password": "elpapuNigga",
    "repeat_password": "elpapuNigga",
    "email": "lenny_music@gmail.com",
    "phone": 7896679
}

###
POST http://localhost:5000/users/logIn
Content-Type: application/json

{
    "email": "lenny_music@gmail.com",
    "password": "elpapuNigga"
}

###
POST http://localhost:5000/users/logIn
Content-Type: application/json

{   
    "email": "delilah_resto@gmail.com",
    "password": "delilahKey1234"
}


###
PUT http://localhost:5000/users/updateUser/2
Authorization: bearer -Admin token here-
Content-Type: application/json

{
    "isActive": true
}