###
GET http://localhost:5000/users/allUsers
Authorization: bearer -Token admin here-

###
POST http://localhost:5000/users/logIn
Content-Type: application/json

{
    "email": "lenny_music@gmail.com",
    "password": "elpapuNigga"
}

###
POST http://localhost:5000/users/logIn
Content-Type: application/json

{   
    "email": "delilah_resto@gmail.com",
    "password": "delilahKey1234"
}


###
PUT http://localhost:5000/users/updateUser/2
Authorization: bearer -Token admin here-
Content-Type: application/json

{
    "isActive": true
}